### ISSUE TITLE
OpenID & checkid_setup not working in Node

### ISSUE THREAD

**Issue by adrien-f** [dennisreimann/masquerade#33]
Hello !

I am currently using masquerade as our OpenID provider for our forum and wiki and I'm currently trying to integrate it with a NodeJS application.

Following the example provided with the library here: http://passportjs.org/guide/openid.html, and trying to submit with my OpenID in masquerade, I get this error:

> Application Error
> 
> Something went wrong - sorry for that!
> We have been informed and will fix this error as soon as possible.

And here's the trace message in the logs:

``` ruby
Started GET "/server?openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.claimed_id=http%3A%2F%2Fopenid.precipicegames.com%2Fsakacoco&openid.identity=http%3A%2F%2Fopenid.precipicegames.com%2Fsakacoco&openid.assoc_handle=%7BHMAC-SHA256%7D%7B4f8ac384%7D%7Bf9xUpg%3D%3D%7D&openid.return_to=http%3A%2F%2Fprecipicegames.com%3A3002%2Fauth%2Fopenid%2Freturn&openid.realm=http%3A%2F%2Fprecipicegames.com%2F" for 90.11.20.133 at Sun Apr 15 08:48:05 -0400 2012
  Processing by ServerController#index as HTML
  Parameters: {"openid.claimed_id"=>"http://openid.precipicegames.com/sakacoco", "openid.mode"=>"checkid_setup", "openid.ns"=>"http://specs.openid.net/auth/2.0", "openid.return_to"=>"http://precipicegames.com:3002/auth/openid/return", "openid.identity"=>"http://openid.precipicegames.com/sakacoco", "openid.realm"=>"http://precipicegames.com/", "openid.assoc_handle"=>"{HMAC-SHA256}{4f8ac384}{f9xUpg==}", "controller"=>"server", "action"=>"index"}
Completed 500 Internal Server Error in 5ms

NoMethodError (undefined method `h' for #<ServerController:0x7f6f0c3efdc8>):
  app/controllers/server_controller.rb:207:in `render_openid_error'
  activesupport (3.0.10) lib/active_support/rescuable.rb:79:in `call'
  activesupport (3.0.10) lib/active_support/rescuable.rb:79:in `rescue_with_handler'
  actionpack (3.0.10) lib/action_controller/metal/rescue.rb:12:in `rescue_with_handler'
  actionpack (3.0.10) lib/action_controller/metal/rescue.rb:19:in `process_action'
  actionpack (3.0.10) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  activesupport (3.0.10) lib/active_support/notifications.rb:52:in `instrument'
  activesupport (3.0.10) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  activesupport (3.0.10) lib/active_support/notifications.rb:52:in `instrument'
  actionpack (3.0.10) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.0.10) lib/abstract_controller/base.rb:119:in `process'
  actionpack (3.0.10) lib/abstract_controller/rendering.rb:41:in `process'
  actionpack (3.0.10) lib/action_controller/metal.rb:138:in `dispatch'
  actionpack (3.0.10) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.0.10) lib/action_controller/metal.rb:178
  actionpack (3.0.10) lib/action_dispatch/routing/route_set.rb:62:in `call'
  actionpack (3.0.10) lib/action_dispatch/routing/route_set.rb:62:in `dispatch'
  actionpack (3.0.10) lib/action_dispatch/routing/route_set.rb:27:in `call'
  rack-mount (0.6.14) lib/rack/mount/route_set.rb:148:in `call'
  rack-mount (0.6.14) lib/rack/mount/code_generation.rb:93:in `recognize'
  rack-mount (0.6.14) lib/rack/mount/code_generation.rb:68:in `optimized_each'
  rack-mount (0.6.14) lib/rack/mount/code_generation.rb:92:in `recognize'
  rack-mount (0.6.14) lib/rack/mount/route_set.rb:139:in `call'
  actionpack (3.0.10) lib/action_dispatch/routing/route_set.rb:493:in `call'
  actionpack (3.0.10) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  actionpack (3.0.10) lib/action_dispatch/middleware/head.rb:14:in `call'
  rack (1.2.4) lib/rack/methodoverride.rb:24:in `call'
  actionpack (3.0.10) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.0.10) lib/action_dispatch/middleware/flash.rb:182:in `call'
  actionpack (3.0.10) lib/action_dispatch/middleware/session/abstract_store.rb:149:in `call'
  actionpack (3.0.10) lib/action_dispatch/middleware/cookies.rb:302:in `call'
  activerecord (3.0.10) lib/active_record/query_cache.rb:32:in `call'
  activerecord (3.0.10) lib/active_record/connection_adapters/abstract/query_cache.rb:28:in `cache'
  activerecord (3.0.10) lib/active_record/query_cache.rb:12:in `cache'
  activerecord (3.0.10) lib/active_record/query_cache.rb:31:in `call'
  activerecord (3.0.10) lib/active_record/connection_adapters/abstract/connection_pool.rb:354:in `call'
  actionpack (3.0.10) lib/action_dispatch/middleware/callbacks.rb:46:in `call'
  activesupport (3.0.10) lib/active_support/callbacks.rb:416:in `_run_call_callbacks'
  actionpack (3.0.10) lib/action_dispatch/middleware/callbacks.rb:44:in `call'
  rack (1.2.4) lib/rack/sendfile.rb:106:in `call'
  actionpack (3.0.10) lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
  actionpack (3.0.10) lib/action_dispatch/middleware/show_exceptions.rb:47:in `call'
  railties (3.0.10) lib/rails/rack/logger.rb:13:in `call'
  rack (1.2.4) lib/rack/runtime.rb:17:in `call'
  activesupport (3.0.10) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.2.4) lib/rack/lock.rb:11:in `call'
  rack (1.2.4) lib/rack/lock.rb:11:in `synchronize'
  rack (1.2.4) lib/rack/lock.rb:11:in `call'
  railties (3.0.10) lib/rails/application.rb:168:in `call'
  railties (3.0.10) lib/rails/application.rb:77:in `send'
  railties (3.0.10) lib/rails/application.rb:77:in `method_missing'
  /usr/lib/ruby/1.8/phusion_passenger/rack/request_handler.rb:95:in `process_request'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
  /usr/lib/ruby/1.8/phusion_passenger/rack/application_spawner.rb:118:in `run'
  /usr/lib/ruby/1.8/phusion_passenger/rack/application_spawner.rb:69:in `spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/utils.rb:184:in `safe_fork'
  /usr/lib/ruby/1.8/phusion_passenger/rack/application_spawner.rb:62:in `spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/rack/application_spawner.rb:45:in `spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:159:in `spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:287:in `handle_spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `__send__'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `main_loop'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
  /usr/lib/phusion_passenger/passenger-spawn-server:61

I'm available to you if you need more informations and details, thanks !
```

**Comment by dennisreimann** [comment]
Can you try the latest version (I fixed the "undefined method `h'" error) and see what error message comes up?
